language: csharp
mono: none
dotnet: 2.2.101
dist: bionic
sudo: false
before_script:
 - dotnet tool install -g coveralls.net
script:
 - dotnet build ./DiceTower
 - dotnet test ./DiceTower.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - csmacnz.Coveralls --opencover -i ./DiceTower.Tests/coverage.opencover.xml --useRelativePaths
